include $(APPDIR)/Make.defs

# ADC example

MAINSRC = awd_pwm_demo_main.c

# application info

PROGNAME = awd_pwm_demo
PRIORITY = SCHED_PRIORITY_DEFAULT
STACKSIZE = $(CONFIG_DEFAULT_TASK_STACKSIZE)
MODULE = $(CONFIG_EXAMPLES_AWD_PWM_DEMO)

include $(APPDIR)/Application.mk
